### ISSUE TITLE
[Feature request] Ctrl-K to quick-select rooms

### ISSUE THREAD

**Issue by zwieberl** [DevinR528/rumatui#9]
Like implemented in Element, it would be nice to be able to switch to rooms based on quick filtering. Just hitting CTRL-k and typing the first few letters of the desired room.
The room-list on the left should then filter out only those rooms that begin with the given search-string. Up and Down could still be used to select from there. 
For searching, it might even be cool to use [sublime_fuzzy](https://github.com/Schlechtwetterfront/fuzzy-rs), for typo-guarding and better results with less keystrokes.

**Comment by DevinR528** [comment]
Ooo that is a great idea! The `fuzzy-rs` crate could also be used to implement message search at some point! If you would be interested in submitting a PR I could point you about where I think this may fit. If not I'll probably start working on this, this weekend!

**Comment by zwieberl** [comment]
In principle, I could have a look, but I don't think i will have much time for it before this weekend

**Comment by DevinR528** [comment]
I'll let you know when I get started so I don't step on any toes, just in case.

**Comment by zwieberl** [comment]
Just FYI: I started a bit on this. Added it to the RoomsWidget for now.

**Comment by DevinR528** [comment]
Sweet!! That's about where I was thinking also. Sorry about the code being a bit messy :roll_eyes:. If you have any questions don't hesitate to ask and if you want to open a draft PR or whatever works!

**Comment by DevinR528** [comment]
Closed via #10
